# This file was generated by GoReleaser. DO NOT EDIT.
cask "forecast-ledger" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "0d796a8449abb5209c27658ee38d0f566c6329318de16dc5615f5c609ea65dad"
      url "https://github.com/chaoscondensate/cli/releases/download/v#{version}/forecast-ledger_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/chaoscondensate/cli/"
    end
    on_intel do
      sha256 "6a53d2d0db68cbbe74ddf6c1ea3034171ec27578896eb28641c362527e0eae39"
      url "https://github.com/chaoscondensate/cli/releases/download/v#{version}/forecast-ledger_#{version}_darwin_x86_64.tar.gz",
        verified: "github.com/chaoscondensate/cli/"
    end
  end
  on_linux do
    on_arm do
      sha256 "53882a4cc8e9a298ff1bf782d2389f683f6a1382f607a6c67bf35113f039d60a"
      url "https://github.com/chaoscondensate/cli/releases/download/v#{version}/forecast-ledger_#{version}_linux_arm64.tar.gz",
        verified: "github.com/chaoscondensate/cli/"
    end
    on_intel do
      sha256 "8fdd97d689edc6767772e22a6277b5ee1c7531679ab17f34b110506fe53ef1c1"
      url "https://github.com/chaoscondensate/cli/releases/download/v#{version}/forecast-ledger_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/chaoscondensate/cli/"
    end
  end

  name "forecast-ledger"
  desc "Create and verify portable forecast evidence"
  homepage "https://chaoscondensate.com/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forecast-ledger"

  preflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/forecast-ledger"]
      system_command "/usr/bin/codesign", args: ["--force", "--sign", "-", "#{staged_path}/forecast-ledger"]
    end
  end
  generate_completions_from_executable "forecast-ledger", "completion",
    base_name: "forecast-ledger",
    shells: [:bash, :zsh, :fish]

  # No zap stanza required

  caveats <<~EOS
    Documentation and project context:
      https://chaoscondensate.com/
  EOS
end
