# This file was generated by the forecast-ledger release workflow. DO NOT EDIT.
class ForecastLedger < Formula
  desc "Create and verify portable forecast evidence"
  homepage "https://chaoscondensate.com/"
  version "0.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chaoscondensate/cli/releases/download/v0.6.1/forecast-ledger_0.6.1_darwin_arm64.tar.gz"
      sha256 "27f896cd4edeef9e757de9eebfbe37817e8a492d450076834f1ca68fd7c36c41"
    else
      url "https://github.com/chaoscondensate/cli/releases/download/v0.6.1/forecast-ledger_0.6.1_darwin_x86_64.tar.gz"
      sha256 "55247e7a232dee3f31765a4a8019f07f7f6672895b7fea73930ac297cc86434a"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chaoscondensate/cli/releases/download/v0.6.1/forecast-ledger_0.6.1_linux_arm64.tar.gz"
      sha256 "3fae4f5f7da6303122f26e51f510997f5b8f06075754bad58a1aef648cf3d16d"
    else
      url "https://github.com/chaoscondensate/cli/releases/download/v0.6.1/forecast-ledger_0.6.1_linux_x86_64.tar.gz"
      sha256 "04bdb2552ee57101bca3cdf77aadf337ba5a99fecd40462fe21a09f3bc2cb734"
    end
  end

  def install
    bin.install "forecast-ledger"
    if OS.mac?
      system "/usr/bin/xattr", "-cr", bin/"forecast-ledger"
      system "/usr/bin/codesign", "--force", "--sign", "-", bin/"forecast-ledger"
    end
    generate_completions_from_executable(bin/"forecast-ledger", "completion")
  end

  test do
    output = shell_output("#{bin}/forecast-ledger version --json")
    assert_match "\"version\":\"#{version}\"", output
  end
end
