# This file was generated by the forecast-ledger release workflow. DO NOT EDIT.
class ForecastLedger < Formula
  desc "Create and verify portable forecast evidence"
  homepage "https://chaoscondensate.com/"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chaoscondensate/cli/releases/download/v0.3.1/forecast-ledger_0.3.1_darwin_arm64.tar.gz"
      sha256 "3c9d25a04fe4a3ba4fd09eb0be19da2b2c43a699097ed79a6fabc78c81f6a0ea"
    else
      url "https://github.com/chaoscondensate/cli/releases/download/v0.3.1/forecast-ledger_0.3.1_darwin_x86_64.tar.gz"
      sha256 "cd99024abce68fcb0c3f94f2eda2b4b2157da82c11ac7bcdd6632bea1298a66a"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chaoscondensate/cli/releases/download/v0.3.1/forecast-ledger_0.3.1_linux_arm64.tar.gz"
      sha256 "d1e1e8b028493057be1272be198859c3151aae4a66ce72eefe88ecd7bc280c38"
    else
      url "https://github.com/chaoscondensate/cli/releases/download/v0.3.1/forecast-ledger_0.3.1_linux_x86_64.tar.gz"
      sha256 "7b47c469f0a1379febe8eaa68b50787fbcb9ccdc3bcfbf826c2533b207d56874"
    end
  end

  def install
    bin.install "forecast-ledger"
    if OS.mac?
      system "/usr/bin/xattr", "-cr", bin/"forecast-ledger"
      system "/usr/bin/codesign", "--force", "--sign", "-", bin/"forecast-ledger"
    end
    generate_completions_from_executable(bin/"forecast-ledger", "completion")
  end

  test do
    output = shell_output("#{bin}/forecast-ledger version --json")
    assert_match "\"version\":\"#{version}\"", output
  end
end
