# This file was generated by the forecast-ledger release workflow. DO NOT EDIT.
class ForecastLedger < Formula
  desc "Create and verify portable forecast evidence"
  homepage "https://chaoscondensate.com/"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/chaoscondensate/cli/releases/download/v0.6.0/forecast-ledger_0.6.0_darwin_arm64.tar.gz"
      sha256 "f412a5a748145ab7e0431e67b974bbd6c4f7603e0f69540c712bbeab641ba640"
    else
      url "https://github.com/chaoscondensate/cli/releases/download/v0.6.0/forecast-ledger_0.6.0_darwin_x86_64.tar.gz"
      sha256 "99b433ddbcca8bbef416191bb29fe3c48685d6dac1bc76c36d924aa373b49fa7"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chaoscondensate/cli/releases/download/v0.6.0/forecast-ledger_0.6.0_linux_arm64.tar.gz"
      sha256 "02ce3775ecfe0a2324e2ae2c359a9f29ee7e62abda483071875e5ee9f25ca5f5"
    else
      url "https://github.com/chaoscondensate/cli/releases/download/v0.6.0/forecast-ledger_0.6.0_linux_x86_64.tar.gz"
      sha256 "2e56f504da58b99c7ea1a93c190b14bedb9ca28bf3f9f24e2c614add19e4e252"
    end
  end

  def install
    bin.install "forecast-ledger"
    if OS.mac?
      system "/usr/bin/xattr", "-cr", bin/"forecast-ledger"
      system "/usr/bin/codesign", "--force", "--sign", "-", bin/"forecast-ledger"
    end
    generate_completions_from_executable(bin/"forecast-ledger", "completion")
  end

  test do
    output = shell_output("#{bin}/forecast-ledger version --json")
    assert_match "\"version\":\"#{version}\"", output
  end
end
